import { chromium } from "/Users/kushagradhawan/Code/kookie-ui-v2/node_modules/.pnpm/playwright@1.62.1/node_modules/playwright/index.mjs";
const [url, sel, mode] = process.argv.slice(2);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 1200 }, deviceScaleFactor: 2 });
await p.goto(url, { waitUntil: "networkidle" });
await p.evaluate((m) => document.documentElement.setAttribute("data-appearance", m), mode);
await p.waitForTimeout(1500);
const el = p.locator(sel).first();
await el.scrollIntoViewIfNeeded();
await p.waitForTimeout(300);
const box = await el.boundingBox();
const buf = await p.screenshot({ clip: { x: box.x + box.width/2, y: box.y - 3, width: 1, height: 12 } });
const reader = await b.newPage();
const prof = await reader.evaluate(async (b64) => {
  const img = new Image(); img.src = "data:image/png;base64," + b64; await img.decode();
  const c = document.createElement("canvas"); c.width = img.width; c.height = img.height;
  const ctx = c.getContext("2d"); ctx.drawImage(img, 0, 0);
  const d = ctx.getImageData(0,0,img.width,img.height).data;
  const out = []; for (let y=0;y<img.height;y++){const i=y*img.width*4; out.push(d[i]);} return out;
}, buf.toString("base64"));
console.log(sel, mode, JSON.stringify(box.width)+"x"+box.height, prof.join(" "));
await b.close();
